const KEY="keiba-note-records-v1";
let editId=null, periodMode="month", calendarDate=new Date(), supabaseClient=null, session=null, cloudReady=false;
const $=x=>document.getElementById(x);
function toNumber(v){if(typeof v==="number") return Number.isFinite(v)?v:0;if(v===null||v===undefined||v==="") return 0;const n=Number(String(v).replace(/,/g,""));return Number.isFinite(n)?n:0}
function normalizeRecord(r,i){return {id:r&&r.id!=null?String(r.id):String(Date.now()+i),date:typeof r?.date==="string"&&r.date?r.date.slice(0,10):"",course:typeof r?.course==="string"&&r.course?r.course:"その他",race:toNumber(r?.race),raceName:typeof r?.raceName==="string"?r.raceName.trim():"",raceCondition:typeof r?.raceCondition==="string"?r.raceCondition.trim():"",distance:typeof r?.distance==="string"?r.distance.trim():"",surface:typeof r?.surface==="string"?r.surface.trim():"",startTime:typeof r?.startTime==="string"?r.startTime.trim():"",raceKey:typeof r?.raceKey==="string"?r.raceKey.trim():"",meeting:typeof r?.meeting==="string"?r.meeting.trim():"",type:typeof r?.type==="string"&&r.type.trim()&&r.type!=="undefined"?r.type:"その他",horses:typeof r?.horses==="string"?r.horses.trim():"",inv:toNumber(r?.inv),ret:toNumber(r?.ret),memo:typeof r?.memo==="string"?r.memo:""}}
function loadLocal(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"[]");const arr=Array.isArray(raw)?raw:[];const normalized=arr.map(normalizeRecord);localStorage.setItem(KEY,JSON.stringify(normalized));return normalized}catch(e){return []}}
let data=loadLocal();
const yen=x=>"¥"+Math.round(toNumber(x)).toLocaleString("ja-JP");
const sign=x=>{x=toNumber(x);return(x>=0?"+":"")+yen(x)};
const cls=x=>toNumber(x)>=0?"positive":"negative";
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(data))}
function stats(a){const inv=a.reduce((s,r)=>s+toNumber(r.inv),0),ret=a.reduce((s,r)=>s+toNumber(r.ret),0),hit=a.filter(r=>toNumber(r.ret)>0).length;return{inv,ret,p:ret-inv,rate:inv?ret/inv*100:0,hitRate:a.length?hit/a.length*100:0,n:a.length}}
function render(){const s=stats(data);$("summary").innerHTML=`<div class="card"><span>累計収支</span><b class="${cls(s.p)}">${sign(s.p)}</b><small>投資 ${yen(s.inv)}</small></div><div class="card"><span>回収率</span><b>${s.rate.toFixed(1)}%</b></div><div class="card"><span>的中率</span><b>${s.hitRate.toFixed(1)}%</b></div><div class="card"><span>記録馬券</span><b>${s.n}</b></div>`;renderPeriod();renderBets();renderCourses();renderRecords();renderRanks();draw(false);renderCalendar()}
function renderPeriod(){const n=new Date();let title,arr;if(periodMode==="year"){const key=String(n.getFullYear());arr=data.filter(r=>r.date.startsWith(key));title=n.getFullYear()+"年の成績"}else{const key=n.getFullYear()+"-"+String(n.getMonth()+1).padStart(2,"0");arr=data.filter(r=>r.date.startsWith(key));title=n.getFullYear()+"年"+(n.getMonth()+1)+"月の成績"}const s=stats(arr);$("periodTitle").textContent=title;$("periodStats").innerHTML=[["投資額",yen(s.inv),""],["払戻額",yen(s.ret),""],["収支",sign(s.p),cls(s.p)],["回収率",s.rate.toFixed(1)+"%",""],["的中率",s.hitRate.toFixed(1)+"%",""],["記録馬券",s.n,""]].map(x=>`<div class="stat"><span>${x[0]}</span><b class="${x[2]}">${x[1]}</b></div>`).join("")}
function renderBets(){const types=[...new Set(data.map(r=>r.type||"その他"))];$("bets").innerHTML=types.length?types.map(t=>{const a=data.filter(r=>(r.type||"その他")===t),s=stats(a);return`<div class="bet"><h3>${t}</h3><p><span>投資</span><b>${yen(s.inv)}</b></p><p><span>払戻</span><b>${yen(s.ret)}</b></p><p><span>回収率</span><b>${s.rate.toFixed(1)}%</b></p><p><span>的中率</span><b>${s.hitRate.toFixed(1)}%</b></p><strong class="${cls(s.p)}">${sign(s.p)}</strong></div>`}).join(""):"<p class='muted'>データがありません。</p>"}
function renderCourses(){const courses=[...new Set(data.map(r=>r.course||"その他"))];$("courses").innerHTML=courses.length?courses.map(c=>{const a=data.filter(r=>(r.course||"その他")===c),s=stats(a);return`<div class="courseCard"><h3>${c}</h3><div><span>投資</span><b>${yen(s.inv)}</b></div><div><span>払戻</span><b>${yen(s.ret)}</b></div><div><span>収支</span><b class="${cls(s.p)}">${sign(s.p)}</b></div><div><span>回収率</span><b>${s.rate.toFixed(1)}%</b></div><div><span>的中率</span><b>${s.hitRate.toFixed(1)}%</b></div><small>${s.n}馬券</small></div>`}).join(""):"<p class='muted'>データがありません。</p>"}
function renderRanks(){const grouped=[...new Set(data.map(r=>r.type||"その他"))].map(t=>{const s=stats(data.filter(r=>(r.type||"その他")===t));return{t,...s}}).filter(x=>x.n);const ret=[...grouped].sort((a,b)=>b.rate-a.rate).slice(0,5),hit=[...grouped].sort((a,b)=>b.hitRate-a.hitRate).slice(0,5);const row=(x,i,key,suffix)=>`<div class="rank"><b>${i+1}</b><span>${x.t}</span><strong>${x[key].toFixed(1)}${suffix}</strong><small>${x.n}件</small></div>`;$("returnRank").innerHTML=ret.length?ret.map((x,i)=>row(x,i,"rate","%")).join(""):"<p class='muted'>データがありません。</p>";$("hitRank").innerHTML=hit.length?hit.map((x,i)=>row(x,i,"hitRate","%")).join(""):"<p class='muted'>データがありません。</p>"}
function renderRecords(){const el=$("records");el.innerHTML=data.length?[...data].sort((a,b)=>b.date.localeCompare(a.date)||String(b.id).localeCompare(String(a.id))).map(r=>{const p=toNumber(r.ret)-toNumber(r.inv);const horse=r.horses?` / 馬番 ${escapeHtml(r.horses)}`:"";const rn=r.raceName?` / ${escapeHtml(r.raceName)}`:"";return`<div class="record"><div class="muted">${r.date}</div><div><b>${escapeHtml(r.course)}${r.race}R　${escapeHtml(r.type)}</b><div class="muted">${rn}${horse||" / 馬番 未入力"} / ${escapeHtml(r.memo||"メモなし")} / 投資 ${yen(r.inv)} → 払戻 ${yen(r.ret)}</div><div class="actions"><button data-e="${r.id}">編集</button><button data-d="${r.id}">削除</button></div></div><b class="${cls(p)}">${sign(p)}</b></div>`}).join(""):"<p class='muted historyEmpty'>まだ収支データがありません。</p>"}
let chartAnimationId=0,chartRainbowPhase=0;
function draw(animateWhenVisible=false){const c=$("chart"),w=c.clientWidth||800,h=290,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;const x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);const n=+$('months').value,now=new Date(),ms=[];for(let i=n-1;i>=0;i--){const q=new Date(now.getFullYear(),now.getMonth()-i,1);ms.push(q.getFullYear()+"-"+String(q.getMonth()+1).padStart(2,"0"))}const v=ms.map(k=>data.filter(r=>r.date.startsWith(k)).reduce((s,r)=>s+toNumber(r.ret)-toNumber(r.inv),0));const rawMax=Math.max(...v,0),rawMin=Math.min(...v,0),rawRange=Math.max(rawMax-rawMin,1),pad=Math.max(rawRange*.16,1000),mx=rawMax+pad,mn=rawMin-pad,range=mx-mn,L=55,R=15,T=22,B=38,pw=w-L-R,ph=h-T-B,zero=T+(mx)/range*ph;const drawFrame=(progress=1)=>{x.clearRect(0,0,w,h);x.strokeStyle="#e5e7eb";x.fillStyle="#6b7280";x.font="12px sans-serif";x.textAlign="right";[mx,0,mn].forEach(q=>{const y=T+(mx-q)/range*ph;x.beginPath();x.moveTo(L,y);x.lineTo(w-R,y);x.stroke();x.fillText((q>=0?"+":"")+yen(q),L-7,y+4)});const gap=pw/n,bw=Math.max(7,gap*.5);x.textAlign="center";v.forEach((q,i)=>{const xx=L+gap*i+gap/2,target=T+(mx-q)/range*ph,y=zero+(target-zero)*progress;if(q>0){const g=x.createLinearGradient(xx-bw/2,Math.min(y,zero),xx+bw/2,Math.max(y,zero));for(let k=0;k<=12;k++){const hue=(chartRainbowPhase*70+k*30+i*18)%360;g.addColorStop(k/12,`hsl(${hue} 85% 52%)`)}x.fillStyle=g;x.fillRect(xx-bw/2,Math.min(y,zero),bw,Math.abs(y-zero))}else if(q<0){x.fillStyle="#dc2626";x.fillRect(xx-bw/2,Math.min(y,zero),bw,Math.abs(y-zero))}x.fillStyle="#6b7280";x.fillText(ms[i].slice(5).replace("-","/"),xx,h-14)})};cancelAnimationFrame(chartAnimationId);if(!animateWhenVisible){drawFrame(1);return}const startTime=performance.now(),duration=650;const animate=(nowTime)=>{const p=Math.min(1,(nowTime-startTime)/duration),ease=1-Math.pow(1-p,3);chartRainbowPhase=nowTime/1000;drawFrame(ease);chartAnimationId=requestAnimationFrame(animate)};chartAnimationId=requestAnimationFrame(animate)}
async function loadRaceDates(){if(scheduleDatePromise)return scheduleDatePromise;scheduleDatePromise=(async()=>{try{const url=new URL("./data/jra-schedule.json",document.baseURI);url.searchParams.set("calendar",Date.now());const res=await fetch(url,{cache:"no-store"});if(!res.ok)throw new Error("schedule fetch failed");const obj=await res.json();const rows=Array.isArray(obj)?obj:(Array.isArray(obj?.races)?obj.races:[]);const dates=new Set();rows.forEach(r=>{const d=String(r.date||"").slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(d))dates.add(d)});window.KEIBA_RACE_DATES=dates;renderCalendar()}catch(e){window.KEIBA_RACE_DATES=new Set()}})();return scheduleDatePromise}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$("calendarTitle").textContent=y+"年"+(m+1)+"月";const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),daily={};data.forEach(r=>{if(r.date.startsWith(y+"-"+String(m+1).padStart(2,"0"))){const d=Number(r.date.slice(8,10));(daily[d]||(daily[d]=[])).push(r)} });let html=["日","月","火","水","木","金","土"].map(x=>`<div class="calHead">${x}</div>`).join("");for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const rows=daily[d]||[],p=rows.reduce((s,r)=>s+toNumber(r.ret)-toNumber(r.inv),0);const dateKey=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;const has=rows.length?" hasData":"";const raceDay=window.KEIBA_RACE_DATES.has(dateKey)?" raceDay":"";html+=`<div class="day ${p>0?'up':p<0?'down':''}${has}${raceDay}" data-date="${dateKey}" ${rows.length?'tabindex="0" role="button"':''}><span>${d}</span>${rows.length?`<b>${p>=0?"+":""}${Math.round(p).toLocaleString("ja-JP")}</b>`:""}</div>`}$("calendar").innerHTML=html}
function openHistory(){renderRecords();$("historyModal").classList.remove("hide")}
function closeHistory(){$("historyModal").classList.add("hide")}
function openCalendarDetail(date){const rows=[...data].filter(r=>r.date===date).sort((a,b)=>String(a.id).localeCompare(String(b.id)));const total=rows.reduce((s,r)=>s+toNumber(r.ret)-toNumber(r.inv),0);$("calendarDetailTitle").textContent=date.replace(/^(\d{4})-(\d{2})-(\d{2})$/,"$1年$2月$3日")+"の内訳";$("calendarDetail").innerHTML=rows.length?`<div class="calendarDetailList">${rows.map(r=>{const p=toNumber(r.ret)-toNumber(r.inv);const rn=r.raceName?` / ${escapeHtml(r.raceName)}`:"";const horse=r.horses?` / 馬番 ${escapeHtml(r.horses)}`:"";return`<div class="calendarDetailItem"><div class="calendarDetailItemTop"><b>${escapeHtml(r.course)}${r.race}R　${escapeHtml(r.type)}</b><b class="${cls(p)}">${sign(p)}</b></div><div class="detailMeta">${rn}${horse||" / 馬番 未入力"}<br>投資 ${yen(r.inv)} → 払戻 ${yen(r.ret)}<br>${escapeHtml(r.memo||"メモなし")}</div></div>`}).join("")}</div><div class="detailSummary"><b>この日の合計：<span class="${cls(total)}">${sign(total)}</span></b></div>`:"<p class='muted'>この日の収支記録はありません。</p>";$("calendarDetailModal").classList.remove("hide")}
function closeCalendarDetail(){$("calendarDetailModal").classList.add("hide")}
// V5.4.14: race schedule is read only from the repository-hosted JSON.
// The app never contacts JRA or a free proxy from the browser. This keeps
// GitHub Pages/iPhone operation independent of external access restrictions.
window.KEIBA_SCHEDULE=[];window.KEIBA_SELECTED_RACE=null;window.KEIBA_RACE_DATES=new Set();let scheduleDatePromise=null;
function jraDayUrl(date){const [y,m,d]=date.split("-");return `https://www.jra.go.jp/keiba/calendar${y}/${y}/${Number(m)}/${m}${d}.html`}
function setScheduleCourseOptions(items,selected=""){const el=$("course");el.innerHTML=`<option value="">${items.length?"競馬場を選択":"この日の開催データがありません"}</option>`+items.map(x=>`<option value="${escapeHtml(x.course)}">${escapeHtml(x.course)}${x.meeting?`（${escapeHtml(x.meeting)}）`:""}</option>`).join("");el.value=selected||"";el.disabled=!items.length&&!selected}
function resetRaceSelect(){const el=$("race");el.innerHTML='<option value="">競馬場を選択してください</option>';el.disabled=true;$("raceMeta").classList.add("hide");window.KEIBA_SELECTED_RACE=null}
function setRaceOptions(items,selected=""){const el=$("race");el.innerHTML=`<option value="">${items.length?"レースを選択":"レース情報がありません"}</option>`+items.map(x=>{const label=`${x.race}R　${x.raceName||"レース"}${x.distance?`　${x.distance}`:""}${x.surface?` ${x.surface}`:""}${x.startTime?`　${x.startTime}`:""}`;return`<option value="${x.race}">${escapeHtml(label)}</option>`}).join("");el.disabled=!items.length;el.value=selected?String(selected):""}
function showRaceMeta(r){const meta=$("raceMeta");if(!r||!r.race)return meta.classList.add("hide");meta.classList.remove("hide");meta.innerHTML=`<b>${escapeHtml(r.raceName||`${r.race}R`)}</b>${r.raceCondition&&r.raceCondition!==r.raceName?`<span>${escapeHtml(r.raceCondition)}</span>`:""}${r.meeting?`<span>${escapeHtml(r.meeting)}</span>`:""}${r.startTime?`<span>発走 ${escapeHtml(r.startTime)}</span>`:""}<a href="${escapeHtml(jraDayUrl($("date").value))}" target="_blank" rel="noopener">JRA公式番組を見る</a>`}
async function loadBundledSchedule(date){
  try{
    const url=new URL("./data/jra-schedule.json",document.baseURI);url.searchParams.set("v",date);
    const res=await fetch(url.href,{cache:"no-store"});
    if(!res.ok)throw Error(`HTTP ${res.status}`);
    const json=await res.json();
    const races=Array.isArray(json.races)?json.races.filter(r=>r&&r.date===date):[];
    window.KEIBA_SCHEDULE=races;
    const courses=[...new Map(races.map(r=>[r.course,{course:r.course,meeting:r.meeting||""}])).values()];
    setScheduleCourseOptions(courses);
    resetRaceSelect();
    if(courses.length){
      $("scheduleStatus").textContent=`${courses.length}場を表示（保存済みデータ）`;
      $("scheduleStatus").className="scheduleStatus muted";
      $("raceStatus").textContent="競馬場を選ぶとレース名を表示します。";
      return true;
    }
    $("scheduleStatus").textContent="この日の開催データはまだ登録されていません。";
    $("scheduleStatus").className="scheduleStatus muted";
    $("raceStatus").textContent="JRA公式番組ページで最新情報を確認できます。";
    return false;
  }catch(e){
    console.warn("Bundled JRA schedule unavailable",e);
    window.KEIBA_SCHEDULE=[];
    setScheduleCourseOptions([]);resetRaceSelect();
    $("scheduleStatus").textContent="保存済みの開催データを読み込めませんでした。";
    return false;
  }
}
function formatScheduleUpdatedAt(value){
  if(!value)return "未取得";
  const d=new Date(value);
  if(Number.isNaN(d.getTime()))return "日時不明";
  return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d);
}
function renderScheduleMonitor(json){
  const badge=$("scheduleUpdateBadge"),updated=$("scheduleUpdatedAt"),count=$("scheduleRaceCount"),range=$("scheduleDateRange"),note=$("scheduleMonitorNote");
  if(!badge||!updated||!count||!range||!note)return;
  const races=Array.isArray(json?.races)?json.races.filter(r=>r&&r.date):[];
  const dates=[...new Set(races.map(r=>r.date))].sort();
  updated.textContent=formatScheduleUpdatedAt(json?.updatedAt);
  count.textContent=`${races.length.toLocaleString("ja-JP")}レース`;
  range.textContent=dates.length?`${dates[0]} ～ ${dates[dates.length-1]}`:"データなし";
  const t=json?.updatedAt?new Date(json.updatedAt).getTime():NaN;
  const ageHours=Number.isFinite(t)?Math.max(0,(Date.now()-t)/3600000):Infinity;
  badge.className="scheduleUpdateBadge";
  if(!races.length||!Number.isFinite(t)){
    badge.textContent="⚠ 要確認";badge.classList.add("warn");
    note.textContent="レース情報を確認できませんでした。GitHub Actionsの自動更新状況を確認してください。";
  }else if(ageHours<=48){
    badge.textContent="● 自動更新：正常";badge.classList.add("ok");
    note.textContent="最新のレース情報ファイルを読み込んでいます。通常はGitHubでの手動更新は不要です。";
  }else if(ageHours<=72){
    badge.textContent="△ 更新を確認";badge.classList.add("warn");
    note.textContent="最終更新から時間が経過しています。JRAの番組公開状況とGitHub Actionsを確認してください。";
  }else{
    badge.textContent="⚠ データが古い可能性";badge.classList.add("stale");
    note.textContent="最終更新から72時間を超えています。GitHub Actionsの実行結果を確認してください。";
  }
}
async function loadScheduleMonitor(){
  try{
    const url=new URL("./data/jra-schedule.json",document.baseURI);url.searchParams.set("monitor",Date.now());
    const res=await fetch(url.href,{cache:"no-store"});
    if(!res.ok)throw Error(`HTTP ${res.status}`);
    const json=await res.json();
    renderScheduleMonitor(json);
  }catch(e){
    renderScheduleMonitor(null);
    console.warn("Schedule monitor unavailable",e);
  }
}

async function loadJraSchedule(date){
  if(!date)return;
  $("scheduleStatus").textContent="保存済み開催情報を読み込み中…";
  $("scheduleStatus").className="scheduleStatus muted";
  resetRaceSelect();window.KEIBA_SCHEDULE=[];
  await loadBundledSchedule(date);
}

function openScheduleMonitor(){
  const modal=$("scheduleMonitorModal");
  if(!modal)return;
  modal.classList.remove("hide");
  loadScheduleMonitor();
}
function closeScheduleMonitor(){
  const modal=$("scheduleMonitorModal");
  if(modal)modal.classList.add("hide");
}
const scheduleMonitorLink=$("menuScheduleMonitorLink");
if(scheduleMonitorLink)scheduleMonitorLink.addEventListener("click",e=>{
  e.preventDefault();
  $("sideMenu")?.classList.remove("open");
  $("menuBackdrop")?.classList.remove("open");
  openScheduleMonitor();
});
$("closeScheduleMonitor")?.addEventListener("click",closeScheduleMonitor);
$("scheduleMonitorModal")?.addEventListener("click",e=>{
  if(e.target.id==="scheduleMonitorModal")closeScheduleMonitor();
});
document.addEventListener("keydown",e=>{
  if(e.key==="Escape")closeScheduleMonitor();
});

$("date").addEventListener("change",()=>loadJraSchedule($("date").value));$("course").addEventListener("change",()=>{const c=$("course").value;const races=window.KEIBA_SCHEDULE.filter(x=>x.course===c);setRaceOptions(races);$("raceStatus").textContent=races.length?`${races.length}レースを表示しています。`:"レース情報がありません。"});$("race").addEventListener("change",()=>{const r=window.KEIBA_SCHEDULE.find(x=>x.course===$("course").value&&String(x.race)===$("race").value);window.KEIBA_SELECTED_RACE=r||null;showRaceMeta(r)});

function makeBetRow(r={}){const wrap=document.createElement("div");wrap.className="betRow";wrap.innerHTML=`<div class="betRowHead"><b>馬券</b><button type="button" class="removeBetRow">削除</button></div><div class="betRowGrid"><label>馬券種<select class="bet-type"><option>複勝</option><option>ワイド</option><option>単勝</option><option>馬連</option><option>馬単</option><option>三連複</option><option>三連単</option><option>その他</option></select></label><label>馬番<div class="horseInputWrap"><input class="bet-horses" type="text" inputmode="numeric" autocomplete="off" pattern="[0-9\- ]*" placeholder="例：8 / 5-8 / 1-3-7"><button type="button" class="horseHyphen" aria-label="ハイフンを入力">−</button></div></label><label>購入金額<input class="bet-inv" type="number" inputmode="numeric" min="0" step="100" required></label><label>払戻金額<input class="bet-ret" type="number" inputmode="numeric" min="0" step="10" required></label><label class="full">メモ<input class="bet-memo" maxlength="100" placeholder="例：複勝500円"></label></div>`;wrap.querySelector(".bet-type").value=r.type||"複勝";wrap.querySelector(".bet-horses").value=r.horses||"";wrap.querySelector(".bet-inv").value=r.inv??"";wrap.querySelector(".bet-ret").value=r.ret??"";wrap.querySelector(".bet-memo").value=r.memo||"";wrap.querySelector(".horseHyphen").onclick=()=>{const input=wrap.querySelector(".bet-horses");const start=input.selectionStart??input.value.length;const end=input.selectionEnd??start;input.value=input.value.slice(0,start)+"-"+input.value.slice(end);input.focus();input.setSelectionRange(start+1,start+1);};wrap.querySelector(".removeBetRow").onclick=()=>{if($("betRows").children.length>1)wrap.remove()};$("betRows").appendChild(wrap)}
function resetBetRows(){$("betRows").innerHTML="";makeBetRow()}
function open(r=null){editId=r?r.id:null;$("mtitle").textContent=r?"収支を編集":"収支を記録";$("save").textContent=r?"変更を保存":"まとめて記録する";$("date").value=r?r.date:new Date().toISOString().slice(0,10);resetBetRows();if(r){setScheduleCourseOptions([{course:r.course,meeting:r.meeting||""}],r.course);setRaceOptions([{race:r.race,raceName:r.raceName||"",raceCondition:r.raceCondition||"",distance:r.distance||"",surface:r.surface||"",startTime:r.startTime||"",raceKey:r.raceKey||"",meeting:r.meeting||""}],r.race);showRaceMeta(r)}else{setScheduleCourseOptions([]);resetRaceSelect()}if(r){const row=$("betRows").firstElementChild;row.querySelector(".bet-type").value=r.type;row.querySelector(".bet-horses").value=r.horses;row.querySelector(".bet-inv").value=r.inv;row.querySelector(".bet-ret").value=r.ret;row.querySelector(".bet-memo").value=r.memo}$("modal").classList.remove("hide");setTimeout(()=>$("date").focus({preventScroll:true}),50);if(!r)loadJraSchedule($("date").value)}
function close(){ $("modal").classList.add("hide");$("form").reset();$("betRows").innerHTML="";editId=null;setTimeout(()=>window.scrollTo({top:window.scrollY,behavior:"auto"}),0)}
function setStatus(text,kind=""){const el=$("syncStatus");el.textContent=text;el.className="syncStatus "+kind}
function cloudConfigured(){return window.KEIBA_CONFIG&&window.KEIBA_CONFIG.supabaseUrl&&window.KEIBA_CONFIG.supabaseKey&&!window.KEIBA_CONFIG.supabaseUrl.includes("YOUR_")&&!window.KEIBA_CONFIG.supabaseKey.includes("YOUR_")}
async function initCloud(){if(!cloudConfigured()){setStatus("Supabase未設定","warn");$("authMessage").textContent="まずSupabaseプロジェクトを作成し、config.jsにURLとPublishable keyを設定してください。現在は端末内保存で動作します。";return}try{supabaseClient=window.supabase.createClient(window.KEIBA_CONFIG.supabaseUrl,window.KEIBA_CONFIG.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const res=await supabaseClient.auth.getSession();session=res.data.session;await updateAuthUI();if(session)await initialCloudSync();supabaseClient.auth.onAuthStateChange(async(_event,s)=>{session=s;await updateAuthUI();if(s&&_event!=="INITIAL_SESSION")await initialCloudSync()})}catch(e){setStatus("接続エラー","error");$("authMessage").textContent="Supabaseの設定を確認してください。";console.error(e)}}
async function updateAuthUI(){const area=$("accountArea"),box=$("authBox");if(session){area.innerHTML=`<div class="account"><span>${escapeHtml(session.user.email||"")}</span><button id="signOut">ログアウト</button></div>`;box.classList.add("hide");$("authMessage").textContent="クラウド同期中。PC・iPhoneで同じアカウントにログインしてください。";setStatus("クラウド同期中","ok");$("signOut").onclick=async()=>{await supabaseClient.auth.signOut()}}else{area.innerHTML="";box.classList.remove("hide");if(cloudConfigured()){setStatus("未ログイン","warn");$("authMessage").textContent="ログインするとクラウド同期が有効になります。"}}
}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function signIn(){if(!supabaseClient)return alert("Supabaseの設定がまだ完了していません。");const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return alert("メールアドレスとパスワードを入力してください。");const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)alert("ログインできませんでした。\n"+error.message)}
async function signUp(){if(!supabaseClient)return alert("Supabaseの設定がまだ完了していません。");const email=$("email").value.trim(),password=$("password").value;if(!email||password.length<6)return alert("メールアドレスと6文字以上のパスワードを入力してください。");const{error}=await supabaseClient.auth.signUp({email,password});if(error)alert("登録できませんでした。\n"+error.message);else alert("登録処理を開始しました。メール確認が有効な場合は、届いたメールを確認してください。")}
function cloudRow(r,userId){return{user_id:userId,id:String(r.id),date:r.date||"1970-01-01",course:r.course||"その他",race:Math.round(toNumber(r.race)),race_name:r.raceName||"",race_condition:r.raceCondition||"",distance:r.distance||"",surface:r.surface||"",start_time:r.startTime||"",race_key:r.raceKey||"",meeting:r.meeting||"",type:r.type||"その他",horses:r.horses||"",inv:toNumber(r.inv),ret:toNumber(r.ret),memo:r.memo||"",updated_at:new Date().toISOString()}}
function fromCloud(r){return normalizeRecord({id:r.id,date:r.date,course:r.course,race:r.race,raceName:r.race_name,raceCondition:r.race_condition,distance:r.distance,surface:r.surface,startTime:r.start_time,raceKey:r.race_key,meeting:r.meeting,type:r.type,horses:r.horses,inv:r.inv,ret:r.ret,memo:r.memo},0)}
function predictionCloudRow(p,userId){return{user_id:userId,id:String(p.id),date:p.date||"1970-01-01",course:p.course||"その他",race:Math.round(toNumber(p.race)),main:p.main||"",second:p.second||"",third:p.third||"",fukusho:p.fukusho||"",wide:p.wide||"",confidence:toNumber(p.confidence),comment:p.comment||"",result:p.result||"",result_data:p.resultData||{},fukusho_hit:!!p.fukushoHit,wide_hit:!!p.wideHit,result_entered:!!p.resultEntered,updated_at:new Date().toISOString()}}
function predictionFromCloud(r){return normalizePrediction({id:r.id,date:r.date,course:r.course,race:r.race,main:r.main,second:r.second,third:r.third,fukusho:r.fukusho,wide:r.wide,confidence:r.confidence,comment:r.comment,result:r.result,resultData:r.result_data,fukushoHit:r.fukusho_hit,wideHit:r.wide_hit,resultEntered:r.result_entered},0)}
async function syncPredictions(){if(!session||!supabaseClient)return;const{data:rows,error}=await supabaseClient.from("keiba_predictions").select("*").eq("user_id",session.user.id);if(error)throw error;const cloud=(rows||[]).map(predictionFromCloud);if(cloud.length===0&&predictions.length){const{error:e}=await supabaseClient.from("keiba_predictions").upsert(predictions.map(p=>predictionCloudRow(p,session.user.id)),{onConflict:"user_id,id"});if(e)throw e}else if(cloud.length){const ids=new Set(cloud.map(p=>p.id));const missing=predictions.filter(p=>!ids.has(p.id));if(missing.length){const{error:e}=await supabaseClient.from("keiba_predictions").upsert(missing.map(p=>predictionCloudRow(p,session.user.id)),{onConflict:"user_id,id"});if(e)throw e;cloud.push(...missing)}predictions=cloud;savePredictions();renderAi()}await applyJraResults(true)}
async function upsertPredictionCloud(p){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_predictions").upsert(predictionCloudRow(p,session.user.id),{onConflict:"user_id,id"});if(error){console.error(error);setStatus("同期エラー","error");alert("AI予想のクラウド保存に失敗しました。端末には保存されています。\n"+error.message)}else setStatus("同期済み","ok")}
async function deletePredictionCloud(id){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_predictions").delete().eq("user_id",session.user.id).eq("id",String(id));if(error){console.error(error);setStatus("同期エラー","error")}}
async function initialCloudSync(){if(!session||!supabaseClient)return;try{setStatus("同期中…","sync");const{data:rows,error}=await supabaseClient.from("keiba_records").select("*").eq("user_id",session.user.id);if(error)throw error;const cloud=(rows||[]).map(fromCloud);if(cloud.length===0&&data.length>0){const ok=confirm(`この端末には${data.length}件のV4データがあります。クラウドへ移行しますか？\n\n「OK」→既存データをクラウドへ保存\n「キャンセル」→クラウドは空のまま`);if(ok){const payload=data.map(r=>cloudRow(r,session.user.id));const{error:e}=await supabaseClient.from("keiba_records").upsert(payload,{onConflict:"user_id,id"});if(e)throw e;setStatus("同期済み","ok");await syncPredictions();return}}else if(cloud.length>0){const cloudIds=new Set(cloud.map(r=>String(r.id)));const missing=data.filter(r=>!cloudIds.has(String(r.id)));if(missing.length){const{error:e}=await supabaseClient.from("keiba_records").upsert(missing.map(r=>cloudRow(r,session.user.id)),{onConflict:"user_id,id"});if(e)throw e;cloud.push(...missing.map(normalizeRecord))}data=cloud;saveLocal();render()}await syncPredictions();setStatus("同期済み","ok")}catch(e){console.error(e);setStatus("同期エラー","error");$("authMessage").textContent="クラウド同期に失敗しました。端末内データは保持しています。";}}
async function upsertCloud(r){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_records").upsert(cloudRow(r,session.user.id),{onConflict:"user_id,id"});if(error){console.error(error);setStatus("同期エラー","error");alert("クラウド保存に失敗しました。端末内には保存されています。\n"+error.message)}else setStatus("同期済み","ok")}
async function deleteCloud(id){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_records").delete().eq("user_id",session.user.id).eq("id",String(id));if(error){console.error(error);setStatus("同期エラー","error");alert("クラウド削除に失敗しました。\n"+error.message)}}
async function clearCloud(){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_records").delete().eq("user_id",session.user.id);if(error){console.error(error);setStatus("同期エラー","error");alert("クラウド削除に失敗しました。\n"+error.message)}}
async function submitRecords(e){e.preventDefault();const date=$("date").value,course=$("course").value,race=toNumber($("race").value);if(!date||!course||!race)return alert("日付・競馬場・レースを入力してください。");const selected=(window.KEIBA_SCHEDULE||[]).find(x=>x.course===course&&toNumber(x.race)===race)||window.KEIBA_SELECTED_RACE||{};const rows=[...$("betRows").querySelectorAll(".betRow")];if(!rows.length)return alert("馬券を1件以上追加してください。");const base={date,course,race,raceName:selected.raceName||"",raceCondition:selected.raceCondition||"",distance:selected.distance||"",surface:selected.surface||"",startTime:selected.startTime||"",raceKey:selected.raceKey||`${date}-${course}-${race}`,meeting:selected.meeting||""};const records=rows.map((row,i)=>normalizeRecord({id:editId&&i===0?editId:String(Date.now())+"-"+i,...base,type:row.querySelector(".bet-type").value,horses:row.querySelector(".bet-horses").value,memo:row.querySelector(".bet-memo").value.trim(),inv:row.querySelector(".bet-inv").value,ret:row.querySelector(".bet-ret").value},i));if(editId){const idx=data.findIndex(x=>String(x.id)===String(editId));if(idx>=0)data[idx]=records[0];else data.push(records[0]);for(let i=1;i<records.length;i++)data.push(records[i])}else data.push(...records);saveLocal();render();close();for(const r of records)await upsertCloud(r)}
$("add").onclick=()=>open();$("close").onclick=close;$("modal").onclick=e=>{if(e.target.id==="modal")close()};$("addBetRow").onclick=()=>makeBetRow();$("form").onsubmit=submitRecords;
$("records").onclick=async e=>{const b=e.target.closest("button");if(!b)return;const id=b.dataset.e||b.dataset.d;if(b.dataset.e){const r=data.find(x=>String(x.id)===String(id));if(r){closeHistory();open(r)}}else if(confirm("この記録を削除しますか？")){data=data.filter(x=>String(x.id)!==String(id));saveLocal();render();await deleteCloud(id)}};
$("clear").onclick=async()=>{if(data.length&&confirm("すべての収支データを削除します。よろしいですか？")){data=[];saveLocal();render();await clearCloud()}};
$("months").onchange=()=>draw(true);addEventListener("resize",()=>draw(false));document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{periodMode=b.dataset.period;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));renderPeriod()});$("prevMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$("nextMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$("historyToggle").onclick=openHistory;$("closeHistory").onclick=closeHistory;$("historyModal").onclick=e=>{if(e.target.id==="historyModal")closeHistory()};$("calendar").onclick=e=>{const d=e.target.closest(".day.hasData");if(d)openCalendarDetail(d.dataset.date)};$("calendar").onkeydown=e=>{const d=e.target.closest(".day.hasData");if(d&&(e.key==="Enter"||e.key===" ")){e.preventDefault();openCalendarDetail(d.dataset.date)}};$("closeCalendarDetail").onclick=closeCalendarDetail;$("calendarDetailModal").onclick=e=>{if(e.target.id==="calendarDetailModal")closeCalendarDetail()};$("signIn").onclick=signIn;$("signUp").onclick=signUp;
$("exportData").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`keiba-note-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$("importData").onclick=()=>$("fileInput").click();$("fileInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const arr=JSON.parse(await f.text());if(!Array.isArray(arr))throw Error("配列ではありません");const imported=arr.map(normalizeRecord);if(!confirm(`${imported.length}件を復元します。現在のデータに追加・上書きしますか？`))return;const map=new Map(data.map(r=>[String(r.id),r]));imported.forEach(r=>map.set(String(r.id),r));data=[...map.values()];saveLocal();render();if(session&&supabaseClient){const{error}=await supabaseClient.from("keiba_records").upsert(data.map(r=>cloudRow(r,session.user.id)),{onConflict:"user_id,id"});if(error)throw error;setStatus("同期済み","ok")}alert("バックアップを復元しました。") }catch(err){alert("復元できませんでした。JSONバックアップを確認してください。\n"+err.message)}finally{e.target.value=""}};
const PKEY="keiba-note-predictions-v2";
let predictions=[];
let jraResults=[];
let jraResultsUpdatedAt="";
function loadPredictions(){try{const a=JSON.parse(localStorage.getItem(PKEY)||localStorage.getItem("keiba-note-predictions-v1")||"[]");return Array.isArray(a)?a.map(normalizePrediction):[]}catch(e){return []}}
function normalizePrediction(p,i){return{id:p&&p.id!=null?String(p.id):"p"+Date.now()+i,raceKey:String(p?.raceKey||resultKey(p?.date||"",p?.course||"",p?.race||0)),date:String(p?.date||"").slice(0,10),course:String(p?.course||"その他"),race:toNumber(p?.race),raceName:String(p?.raceName||""),raceCondition:String(p?.raceCondition||""),distance:String(p?.distance||""),surface:String(p?.surface||""),fieldSize:toNumber(p?.fieldSize),going:String(p?.going||""),main:String(p?.main||""),second:String(p?.second||""),third:String(p?.third||""),fourth:String(p?.fourth||""),fifth:String(p?.fifth||""),confidence:Math.max(0,Math.min(100,toNumber(p?.confidence))),status:["BUY","HOLD","SKIP"].includes(p?.status)?p.status:"HOLD",comment:String(p?.comment||""),predictionTime:String(p?.predictionTime||new Date().toISOString()),marketSnapshot:p?.marketSnapshot&&typeof p.marketSnapshot==="object"?p.marketSnapshot:{winOdds:String(p?.winOdds||""),placeOdds:String(p?.placeOdds||""),wideOdds:String(p?.wideOdds||""),weight:String(p?.weight||""),weightChange:String(p?.weightChange||""),going:String(p?.going||"")},horseEvaluations:p?.horseEvaluations&&typeof p.horseEvaluations==="object"?p.horseEvaluations:{},resultEntered:false}}
function savePredictions(){localStorage.setItem(PKEY,JSON.stringify(predictions))}
function nums(s){return String(s||"").match(/\d+/g)||[]}
function resultNums(s){return nums(s).slice(0,3)}
function top3Hit(horse,res){return !!horse&&resultNums(res).includes(String(horse).replace(/[^0-9]/g,""))}
function predictionId(date,course,race){return `p-${date}-${course}-${Math.round(toNumber(race))}`}
function resultKey(date,course,race){return `${date}-${course}-${Math.round(toNumber(race))}`}
function findJraResult(p){return jraResults.find(r=>resultKey(r.date,r.course,r.race)===String(p.raceKey||resultKey(p.date,p.course,p.race)))||null}
function runnerFor(result,horse){if(!result||!Array.isArray(result.runners))return null;const n=String(horse||"").replace(/[^0-9]/g,"");return result.runners.find(x=>String(x.horseNo)===n)||null}
function payoutFor(result,type,horse){if(!result?.payouts)return 0;const arr=result.payouts[type]||[];const n=String(horse||"").replace(/[^0-9]/g,"");const row=arr.find(x=>String(x.horses||"").split("-")[0]===n);return row?toNumber(row.payout):0}
function comboPayout(result,a,b){if(!result?.payouts?.wide)return 0;const key=[String(a),String(b)].sort((x,y)=>Number(x)-Number(y)).join("-");const row=result.payouts.wide.find(x=>String(x.horses||"")===key);return row?toNumber(row.payout):0}
function roiForPrediction(p){const r=findJraResult(p);const picks=[p.main,p.second,p.third].filter(Boolean);if(!r?.runners?.length||!picks.length)return{single:null,place:null,wide:null};let singleReturn=0,placeReturn=0;for(const h of picks){singleReturn+=payoutFor(r,"win",h);placeReturn+=payoutFor(r,"place",h)}const widePairs=[];for(let i=0;i<picks.length;i++)for(let j=i+1;j<picks.length;j++)widePairs.push([picks[i],picks[j]]);let wideReturn=0;for(const [a,b] of widePairs)wideReturn+=comboPayout(r,a,b);return{single:singleReturn/(picks.length*100)*100,place:placeReturn/(picks.length*100)*100,wide:widePairs.length?wideReturn/(widePairs.length*100)*100:null}}
function roiText(v){return v==null?"-":`${v.toFixed(1)}%`}
function applyResultToPrediction(p,r){return !!r}
function resultForPrediction(p){return findJraResult(p)}
function actualBetRowsForPrediction(p){return data.filter(r=>String(r.date)===p.date&&String(r.course)===p.course&&toNumber(r.race)===toNumber(p.race))}
function predictionCloudRow(p,userId){return{user_id:userId,id:String(p.id),date:p.date||"1970-01-01",course:p.course||"その他",race:Math.round(toNumber(p.race)),race_key:p.raceKey||resultKey(p.date,p.course,p.race),race_name:p.raceName||"",race_condition:p.raceCondition||"",distance:p.distance||"",surface:p.surface||"",field_size:Math.round(toNumber(p.fieldSize)),going:p.going||"",main:p.main||"",second:p.second||"",third:p.third||"",fourth:p.fourth||"",fifth:p.fifth||"",status:p.status||"HOLD",prediction_time:p.predictionTime||new Date().toISOString(),market_snapshot:p.marketSnapshot||{},horse_evaluations:p.horseEvaluations||{},confidence:toNumber(p.confidence),comment:p.comment||"",updated_at:new Date().toISOString()}}
function predictionFromCloud(r){return normalizePrediction({id:r.id,date:r.date,course:r.course,race:r.race,raceKey:r.race_key,raceName:r.race_name,raceCondition:r.race_condition,distance:r.distance,surface:r.surface,fieldSize:r.field_size,going:r.going,main:r.main,second:r.second,third:r.third,fourth:r.fourth,fifth:r.fifth,status:r.status,predictionTime:r.prediction_time,marketSnapshot:r.market_snapshot,horseEvaluations:r.horse_evaluations,confidence:r.confidence,comment:r.comment},0)}
async function syncPredictions(){if(!session||!supabaseClient)return;const{data:rows,error}=await supabaseClient.from("keiba_predictions").select("*").eq("user_id",session.user.id);if(error)throw error;const cloud=(rows||[]).map(predictionFromCloud);if(cloud.length===0&&predictions.length){const{error:e}=await supabaseClient.from("keiba_predictions").upsert(predictions.map(p=>predictionCloudRow(p,session.user.id)),{onConflict:"user_id,id"});if(e)throw e}else if(cloud.length){const ids=new Set(cloud.map(p=>p.id));const missing=predictions.filter(p=>!ids.has(p.id));if(missing.length){const{error:e}=await supabaseClient.from("keiba_predictions").upsert(missing.map(p=>predictionCloudRow(p,session.user.id)),{onConflict:"user_id,id"});if(e)throw e;cloud.push(...missing)}predictions=cloud;savePredictions();renderAi()} }
async function upsertPredictionCloud(p){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_predictions").upsert(predictionCloudRow(p,session.user.id),{onConflict:"user_id,id"});if(error){console.error(error);setStatus("同期エラー","error");alert("AI予想のクラウド保存に失敗しました。端末には保存されています。\n"+error.message)}else setStatus("同期済み","ok")}
async function deletePredictionCloud(id){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_predictions").delete().eq("user_id",session.user.id).eq("id",String(id));if(error){console.error(error);setStatus("同期エラー","error")}}
async function applyJraResults(){renderAi()}
async function loadJraResults(){try{const url=new URL("./data/jra-results.json",document.baseURI);url.searchParams.set("v",Date.now());const res=await fetch(url,{cache:"no-store"});if(!res.ok)throw new Error("results fetch failed");const obj=await res.json();jraResults=Array.isArray(obj)?obj:(Array.isArray(obj?.results)?obj.results:[]);jraResultsUpdatedAt=obj?.updatedAt||"";window.KEIBA_JRA_RESULTS_UPDATED_AT=jraResultsUpdatedAt;const el=$("aiResultStatus");if(el)el.textContent=jraResults.length?`JRA公式結果：${jraResults.length}レース / 最終更新 ${jraResultsUpdatedAt||"確認中"}`:"JRA公式結果データはまだありません。GitHub Actionsの結果更新後に自動連携されます。";renderAi()}catch(e){jraResults=[];const el=$("aiResultStatus");if(el)el.textContent="JRA結果データを取得できませんでした。次回の自動更新で再試行します。";console.warn("JRA result data unavailable",e)}}
function predictionMarkerHtml(p,mark,horse){const r=resultForPrediction(p);const x=runnerFor(r,horse);if(!x)return `<span class="predictionResultLine">${mark} ${escapeHtml(horse||"-")}：結果待ち</span>`;const win=payoutFor(r,"win",horse),place=payoutFor(r,"place",horse);return `<span class="predictionResultLine">${mark} ${escapeHtml(horse||"-")}：${escapeHtml(String(x.finish))}着 / ${escapeHtml(String(x.popularity))}人気 / 単勝${x.odds!=null?escapeHtml(String(x.odds)):"-"}倍 / 単勝払戻${win?yen(win):"-"} / 複勝${place?yen(place):"-"}</span>`}
function renderAiStats(){const n=predictions.length,withResult=predictions.filter(resultForPrediction);const marks=[['◎','main'],['○','second'],['▲','third'],['△','fourth'],['☆','fifth']];const hit=key=>withResult.length?`${(withResult.filter(p=>top3Hit(p[key],(resultForPrediction(p)?.runners||[]).sort((a,b)=>toNumber(a.finish)-toNumber(b.finish)).slice(0,3).map(x=>x.horseNo).join('-'))).length/withResult.length*100).toFixed(1)}%`:'-';const buys=predictions.filter(p=>p.status==='BUY'),buyRows=buys.flatMap(actualBetRowsForPrediction);const inv=buyRows.reduce((s,r)=>s+toNumber(r.inv),0),ret=buyRows.reduce((s,r)=>s+toNumber(r.ret),0);const avgRoi=k=>{const a=withResult.map(roiForPrediction).map(x=>x[k]).filter(x=>x!=null);return a.length?(a.reduce((s,x)=>s+x,0)/a.length).toFixed(1)+'%':'-'};$('aiStats').innerHTML=`<div class="aiStat"><span>予想レース</span><b>${n}</b></div><div class="aiStat"><span>結果連携済み</span><b>${withResult.length}</b></div><div class="aiStat"><span>買い</span><b>${buys.length}</b></div><div class="aiStat"><span>見送り</span><b>${predictions.filter(p=>p.status==='SKIP').length}</b></div><div class="aiStat"><span>◎3着以内</span><b>${hit('main')}</b></div><div class="aiStat"><span>○3着以内</span><b>${hit('second')}</b></div><div class="aiStat"><span>▲3着以内</span><b>${hit('third')}</b></div><div class="aiStat"><span>△3着以内</span><b>${hit('fourth')}</b></div><div class="aiStat"><span>☆3着以内</span><b>${hit('fifth')}</b></div><div class="aiStat"><span>実購入収支</span><b>${buyRows.length?sign(ret-inv):'-'}</b></div><div class="aiStat"><span>実購入回収率</span><b>${inv?(ret/inv*100).toFixed(1)+'%':'-'}</b></div><div class="aiStat"><span>仮想単勝ROI</span><b>${avgRoi('single')}</b></div>`}
function statusLabel(s){return s==='BUY'?'買い':s==='SKIP'?'見送り':'保留'}
function renderPredictions(){const el=$("predictionList"),arr=[...predictions].sort((a,b)=>b.date.localeCompare(a.date)||toNumber(b.race)-toNumber(a.race));if(!arr.length){el.innerHTML="<p class='muted'>まだAI予想がありません。ChatGPTで予想した内容を登録してください。</p>";return}el.innerHTML=arr.map(p=>{const r=resultForPrediction(p),roi=roiForPrediction(p),bets=actualBetRowsForPrediction(p),status=statusLabel(p.status);const result=r?`<div class="resultBox predictionResult"><b>JRA公式結果</b>${predictionMarkerHtml(p,"◎",p.main)}${predictionMarkerHtml(p,"○",p.second)}${predictionMarkerHtml(p,"▲",p.third)}${predictionMarkerHtml(p,"△",p.fourth)}${predictionMarkerHtml(p,"☆",p.fifth)}<span class="predictionResultLine">仮想ROI：単勝 ${roiText(roi.single)} / 複勝 ${roiText(roi.place)} / ワイド ${roiText(roi.wide)}</span></div>`:`<div class="muted predictionPending">JRA公式結果の自動連携待ちです。</div>`;const market=p.marketSnapshot||{};return `<div class="prediction"><div class="predictionTop"><b>${escapeHtml(p.date)}　${escapeHtml(p.course)}${p.race}R</b><span class="badge ${p.status==='BUY'?'hit':''}">${status}</span></div><div class="muted predictionMeta">${escapeHtml(p.raceName||'レース情報')} ${escapeHtml(p.surface||'')} ${escapeHtml(p.distance||'')} ${escapeHtml(p.raceCondition||'')} / 予想時刻 ${escapeHtml(p.predictionTime?new Date(p.predictionTime).toLocaleString('ja-JP'):'-')}</div><div class="predictionBadges"><span class="badge main">◎ ${escapeHtml(p.main)||'-'}</span><span class="badge">○ ${escapeHtml(p.second)||'-'}</span><span class="badge">▲ ${escapeHtml(p.third)||'-'}</span><span class="badge">△ ${escapeHtml(p.fourth)||'-'}</span><span class="badge">☆ ${escapeHtml(p.fifth)||'-'}</span></div><div class="muted predictionMarket">予想時市場：単勝 ${escapeHtml(market.winOdds||'-')} / 馬体重 ${escapeHtml(market.weight||'-')} ${escapeHtml(market.weightChange||'')} / 馬場 ${escapeHtml(market.going||'-')}</div>${p.comment?`<p class="predictionComment">${escapeHtml(p.comment)}</p>`:""}${bets.length?`<div class="predictionBetLink">実購入：${bets.length}件 / 投資 ${yen(bets.reduce((s,x)=>s+toNumber(x.inv),0))} / 払戻 ${yen(bets.reduce((s,x)=>s+toNumber(x.ret),0))}</div>`:`<div class="muted predictionBetLink">実購入：なし</div>`}${result}<div class="predictionActions"><button data-editpred="${escapeHtml(p.id)}">編集</button><button data-delpred="${escapeHtml(p.id)}">削除</button></div></div>`}).join("")}
function renderAi(){renderAiStats();renderPredictions()}
function fillPrediction(p){$("pDate").value=p.date;$("pCourse").value=p.course;$("pRace").value=p.race;$("pStatus").value=p.status||'HOLD';$("pMain").value=p.main;$("pSecond").value=p.second;$("pThird").value=p.third;$("pFourth").value=p.fourth;$("pFifth").value=p.fifth;const m=p.marketSnapshot||{};$("pWinOdds").value=m.winOdds||'';$("pWeight").value=m.weight||'';$("pWeightChange").value=m.weightChange||'';$("pGoing").value=m.going||'';$("pWideOdds").value=m.wideOdds||'';$("pComment").value=p.comment;$('savePrediction').dataset.edit=p.id;openAiDetails()}
function clearPredictionForm(){['pMain','pSecond','pThird','pFourth','pFifth','pWinOdds','pWeight','pWeightChange','pGoing','pWideOdds','pComment'].forEach(id=>$(id).value='');$("pDate").value=new Date().toISOString().slice(0,10);$("pCourse").value="阪神";$("pRace").value="";$("pStatus").value="HOLD";delete $("savePrediction").dataset.edit}
function selectedRaceForPrediction(){return (window.KEIBA_SCHEDULE||[]).find(x=>x.course===$("pCourse").value&&toNumber(x.race)===toNumber($("pRace").value))||window.KEIBA_SELECTED_RACE||{}}
function collectPrediction(){const selected=selectedRaceForPrediction(), date=$("pDate").value,course=$("pCourse").value,race=$("pRace").value;return normalizePrediction({id:$("savePrediction").dataset.edit||predictionId(date,course,race),date,course,race,raceKey:resultKey(date,course,race),raceName:selected.raceName||"",raceCondition:selected.raceCondition||"",distance:selected.distance||"",surface:selected.surface||"",fieldSize:selected.fieldSize||0,going:$("pGoing").value,main:$("pMain").value,second:$("pSecond").value,third:$("pThird").value,fourth:$("pFourth").value,fifth:$("pFifth").value,status:$("pStatus").value,predictionTime:$("savePrediction").dataset.edit?(predictions.find(x=>x.id===$("savePrediction").dataset.edit)?.predictionTime||new Date().toISOString()):new Date().toISOString(),marketSnapshot:{winOdds:$("pWinOdds").value.trim(),wideOdds:$("pWideOdds").value.trim(),weight:$("pWeight").value.trim(),weightChange:$("pWeightChange").value.trim(),going:$("pGoing").value.trim()},comment:$("pComment").value},0)}
async function savePrediction(){const p=collectPrediction();if(!p.date||!p.course||!p.race||!p.main)return alert('日付・競馬場・R・◎本命は入力してください。');const i=predictions.findIndex(x=>x.id===p.id);if(i>=0)predictions[i]=p;else predictions.push(p);savePredictions();renderAi();clearPredictionForm();await upsertPredictionCloud(p)}
function normalizePredictionLine(line){let cleaned=line.trim().replace(/^[-*•]\s*/, '').replace(/^KEIBA_NOTE\s*:\s*/i,'').trim();if(!cleaned)return null;const parts=cleaned.split('|').map(x=>x.trim());if(parts.length<6)return null;let date=parts[0].replace(/\D/g,'');if(/^\d{8}$/.test(date))date=`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return null;const course=parts[1],race=toNumber(parts[2]),main=parts[3],second=parts[4],third=parts[5],fourth=parts[6]||'',fifth=parts[7]||'',status=['BUY','HOLD','SKIP'].includes((parts[8]||'').toUpperCase())?(parts[8]||'').toUpperCase():'HOLD',comment=parts.slice(9).join('|');if(!course||race<1||race>12||!main)return null;return normalizePrediction({id:predictionId(date,course,race),date,course,race,main,second,third,fourth,fifth,status,comment},0)}
async function parseAiPaste(){const raw=$("aiPasteText").value.trim();if(!raw){alert("AI予想を貼り付けてください。");return}const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const imported=[],errors=[];lines.forEach((line,i)=>{const pred=normalizePredictionLine(line);if(pred)imported.push(pred);else errors.push(i+1)});if(!imported.length){alert("読み込める予想がありません。\n形式：KEIBA NOTE: 20260919|中山|1|7|11|5");return}const map=new Map(predictions.map(p=>[String(p.id),p]));imported.forEach(pred=>map.set(String(pred.id),pred));predictions=[...map.values()];savePredictions();renderAi();if(session&&supabaseClient){try{const{error}=await supabaseClient.from("keiba_predictions").upsert(imported.map(pred=>predictionCloudRow(pred,session.user.id)),{onConflict:"user_id,id"});if(error)throw error;setStatus("同期済み","ok")}catch(err){console.error(err);setStatus("同期エラー","error");alert(`端末には登録しましたが、クラウド保存に失敗しました。\n${err.message}`)}}$("aiPasteModal").classList.add("hide");$("aiPasteText").value="";alert(`${imported.length}レースのAI予想を登録しました。${errors.length?`\n読み込めなかった行：${errors.join(", ")}行目`:""}`)}
function openAiDetails(){$("aiDetails").classList.remove("hide");$("toggleAi").textContent="詳細を隠す"}
function closeAiDetails(){$("aiDetails").classList.add("hide");$("toggleAi").textContent="詳細を表示"}
$("toggleAi").onclick=()=>$("aiDetails").classList.contains("hide")?openAiDetails():closeAiDetails();
$("savePrediction").onclick=savePrediction;$("clearPredictionForm").onclick=clearPredictionForm;$("openAiPaste").onclick=()=>$('aiPasteModal').classList.remove("hide");$("closeAiPaste").onclick=()=>$('aiPasteModal').classList.add("hide");$("aiPasteModal").onclick=e=>{if(e.target.id==="aiPasteModal")$("aiPasteModal").classList.add("hide")};$("importAiPaste").onclick=parseAiPaste;
$("predictionList").onclick=async e=>{const b=e.target.closest("button");if(!b)return;const id=b.dataset.editpred||b.dataset.delpred;if(b.dataset.editpred){const pred=predictions.find(x=>x.id===id);if(pred)fillPrediction(pred)}else if(b.dataset.delpred&&confirm("このAI予想を削除しますか？")){predictions=predictions.filter(x=>x.id!==id);savePredictions();renderAi();await deletePredictionCloud(id)}};
$("menuToggle").onclick=()=>{$("sideMenu").classList.add("open");$("menuBackdrop").classList.add("open")};$("menuClose").onclick=()=>{$("sideMenu").classList.remove("open");$("menuBackdrop").classList.remove("open")};$("menuBackdrop").onclick=()=>{$("sideMenu").classList.remove("open");$("menuBackdrop").classList.remove("open")};document.querySelectorAll("#sideMenu a").forEach(a=>a.onclick=()=>{$("sideMenu").classList.remove("open");$("menuBackdrop").classList.remove("open")});$("menuHistoryLink").onclick=e=>{e.preventDefault();closeHistory();openHistory()};
clearPredictionForm();loadRaceDates();predictions=loadPredictions();renderAi();closeAiDetails();resetBetRows();loadJraResults().then(()=>initCloud());const chartPanel=$("chartPanel");const chartObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){draw(true)}},{threshold:.2});chartObserver.observe(chartPanel);render();
