const KEY="keiba-note-records-v1";
let editId=null, periodMode="month", calendarDate=new Date(), supabaseClient=null, session=null, cloudReady=false;
const $=x=>document.getElementById(x);
function toNumber(v){if(typeof v==="number") return Number.isFinite(v)?v:0;if(v===null||v===undefined||v==="") return 0;const n=Number(String(v).replace(/,/g,""));return Number.isFinite(n)?n:0}
function normalizeRecord(r,i){return {id:r&&r.id!=null?String(r.id):String(Date.now()+i),date:typeof r?.date==="string"&&r.date?r.date.slice(0,10):"",course:typeof r?.course==="string"&&r.course?r.course:"その他",race:toNumber(r?.race),type:typeof r?.type==="string"&&r.type.trim()&&r.type!=="undefined"?r.type:"その他",inv:toNumber(r?.inv),ret:toNumber(r?.ret),memo:typeof r?.memo==="string"?r.memo:""}}
function loadLocal(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"[]");const arr=Array.isArray(raw)?raw:[];const normalized=arr.map(normalizeRecord);localStorage.setItem(KEY,JSON.stringify(normalized));return normalized}catch(e){return []}}
let data=loadLocal();
const yen=x=>"¥"+Math.round(toNumber(x)).toLocaleString("ja-JP");
const sign=x=>{x=toNumber(x);return(x>=0?"+":"")+yen(x)};
const cls=x=>toNumber(x)>=0?"positive":"negative";
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(data))}
function stats(a){const inv=a.reduce((s,r)=>s+toNumber(r.inv),0),ret=a.reduce((s,r)=>s+toNumber(r.ret),0),hit=a.filter(r=>toNumber(r.ret)>0).length;return{inv,ret,p:ret-inv,rate:inv?ret/inv*100:0,hitRate:a.length?hit/a.length*100:0,n:a.length}}
function render(){const s=stats(data);$("summary").innerHTML=`<div class="card"><span>累計収支</span><b class="${cls(s.p)}">${sign(s.p)}</b><small>投資 ${yen(s.inv)}</small></div><div class="card"><span>回収率</span><b>${s.rate.toFixed(1)}%</b></div><div class="card"><span>的中率</span><b>${s.hitRate.toFixed(1)}%</b></div><div class="card"><span>記録レース</span><b>${s.n}</b></div>`;renderPeriod();renderBets();renderCourses();renderRecords();renderRanks();draw();renderCalendar()}
function renderPeriod(){const n=new Date();let title,arr;if(periodMode==="year"){const key=String(n.getFullYear());arr=data.filter(r=>r.date.startsWith(key));title=n.getFullYear()+"年の成績"}else{const key=n.getFullYear()+"-"+String(n.getMonth()+1).padStart(2,"0");arr=data.filter(r=>r.date.startsWith(key));title=n.getFullYear()+"年"+(n.getMonth()+1)+"月の成績"}const s=stats(arr);$("periodTitle").textContent=title;$("periodStats").innerHTML=[["投資額",yen(s.inv),""],["払戻額",yen(s.ret),""],["収支",sign(s.p),cls(s.p)],["回収率",s.rate.toFixed(1)+"%",""],["的中率",s.hitRate.toFixed(1)+"%",""],["記録レース",s.n,""]].map(x=>`<div class="stat"><span>${x[0]}</span><b class="${x[2]}">${x[1]}</b></div>`).join("")}
function renderBets(){const types=[...new Set(data.map(r=>r.type||"その他"))];$("bets").innerHTML=types.length?types.map(t=>{const a=data.filter(r=>(r.type||"その他")===t),s=stats(a);return`<div class="bet"><h3>${t}</h3><p><span>投資</span><b>${yen(s.inv)}</b></p><p><span>払戻</span><b>${yen(s.ret)}</b></p><p><span>回収率</span><b>${s.rate.toFixed(1)}%</b></p><p><span>的中率</span><b>${s.hitRate.toFixed(1)}%</b></p><strong class="${cls(s.p)}">${sign(s.p)}</strong></div>`}).join(""):"<p class='muted'>データがありません。</p>"}
function renderCourses(){const courses=[...new Set(data.map(r=>r.course||"その他"))];$("courses").innerHTML=courses.length?courses.map(c=>{const a=data.filter(r=>(r.course||"その他")===c),s=stats(a);return`<div class="courseCard"><h3>${c}</h3><div><span>投資</span><b>${yen(s.inv)}</b></div><div><span>払戻</span><b>${yen(s.ret)}</b></div><div><span>収支</span><b class="${cls(s.p)}">${sign(s.p)}</b></div><div><span>回収率</span><b>${s.rate.toFixed(1)}%</b></div><div><span>的中率</span><b>${s.hitRate.toFixed(1)}%</b></div><small>${s.n}レース</small></div>`}).join(""):"<p class='muted'>データがありません。</p>"}
function renderRanks(){const grouped=[...new Set(data.map(r=>r.type||"その他"))].map(t=>{const s=stats(data.filter(r=>(r.type||"その他")===t));return{t,...s}}).filter(x=>x.n);const ret=[...grouped].sort((a,b)=>b.rate-a.rate).slice(0,5),hit=[...grouped].sort((a,b)=>b.hitRate-a.hitRate).slice(0,5);const row=(x,i,key,suffix)=>`<div class="rank"><b>${i+1}</b><span>${x.t}</span><strong>${x[key].toFixed(1)}${suffix}</strong><small>${x.n}R</small></div>`;$("returnRank").innerHTML=ret.length?ret.map((x,i)=>row(x,i,"rate","%")).join(""):"<p class='muted'>データがありません。</p>";$("hitRank").innerHTML=hit.length?hit.map((x,i)=>row(x,i,"hitRate","%")).join(""):"<p class='muted'>データがありません。</p>"}
function renderRecords(){const el=$("records");el.innerHTML=data.length?[...data].sort((a,b)=>b.date.localeCompare(a.date)||String(b.id).localeCompare(String(a.id))).map(r=>{const p=toNumber(r.ret)-toNumber(r.inv);return`<div class="record"><div class="muted">${r.date}</div><div><b>${r.course}${r.race}R　${r.type}</b><div class="muted">${r.memo||"メモなし"} / 投資 ${yen(r.inv)} → 払戻 ${yen(r.ret)}</div><div class="actions"><button data-e="${r.id}">編集</button><button data-d="${r.id}">削除</button></div></div><b class="${cls(p)}">${sign(p)}</b></div>`}).join(""):"<p class='muted'>まだ収支データがありません。</p>"}
function draw(){const c=$("chart"),w=c.clientWidth||800,h=290,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;const x=c.getContext("2d");x.scale(d,d);x.clearRect(0,0,w,h);const n=+$('months').value,now=new Date(),ms=[];for(let i=n-1;i>=0;i--){const q=new Date(now.getFullYear(),now.getMonth()-i,1);ms.push(q.getFullYear()+"-"+String(q.getMonth()+1).padStart(2,"0"))}const v=ms.map(k=>data.filter(r=>r.date.startsWith(k)).reduce((s,r)=>s+toNumber(r.ret)-toNumber(r.inv),0));const mx=Math.max(...v,0),mn=Math.min(...v,0),range=Math.max(mx-mn,1),L=55,R=15,T=15,B=38,pw=w-L-R,ph=h-T-B,zero=T+mx/range*ph;x.strokeStyle="#e5e7eb";x.fillStyle="#6b7280";x.font="12px sans-serif";x.textAlign="right";[mx,0,mn].forEach(q=>{const y=T+(mx-q)/range*ph;x.beginPath();x.moveTo(L,y);x.lineTo(w-R,y);x.stroke();x.fillText((q>=0?"+":"")+yen(q),L-7,y+4)});const gap=pw/n,bw=Math.max(7,gap*.5);x.textAlign="center";v.forEach((q,i)=>{const xx=L+gap*i+gap/2,y=T+(mx-q)/range*ph;x.fillStyle=q>=0?"#059669":"#dc2626";x.fillRect(xx-bw/2,Math.min(y,zero),bw,Math.max(Math.abs(y-zero),2));x.fillStyle="#6b7280";x.fillText(ms[i].slice(5).replace("-","/"),xx,h-14)})}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$("calendarTitle").textContent=y+"年"+(m+1)+"月";const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),daily={};data.forEach(r=>{if(r.date.startsWith(y+"-"+String(m+1).padStart(2,"0"))){const d=Number(r.date.slice(8,10));daily[d]=(daily[d]||0)+toNumber(r.ret)-toNumber(r.inv)}});let html=["日","月","火","水","木","金","土"].map(x=>`<div class="calHead">${x}</div>`).join("");for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const p=daily[d]||0;html+=`<div class="day ${p>0?'up':p<0?'down':''}"><span>${d}</span>${daily[d]!==undefined?`<b>${p>=0?"+":""}${Math.round(p).toLocaleString("ja-JP")}</b>`:""}</div>`}$("calendar").innerHTML=html}
function open(r=null){editId=r?r.id:null;$("mtitle").textContent=r?"収支を編集":"収支を記録";$("save").textContent=r?"変更を保存":"記録する";$("date").value=r?r.date:new Date().toISOString().slice(0,10);$("course").value=r?r.course:"";$("race").value=r?r.race:"";$("type").value=r?r.type:"複勝";$("inv").value=r?r.inv:"";$("ret").value=r?r.ret:"";$("memo").value=r?r.memo:"";$("modal").classList.remove("hide")}
function close(){ $("modal").classList.add("hide");$("form").reset();editId=null }
function setStatus(text,kind=""){const el=$("syncStatus");el.textContent=text;el.className="syncStatus "+kind}
function cloudConfigured(){return window.KEIBA_CONFIG&&window.KEIBA_CONFIG.supabaseUrl&&window.KEIBA_CONFIG.supabaseKey&&!window.KEIBA_CONFIG.supabaseUrl.includes("YOUR_")&&!window.KEIBA_CONFIG.supabaseKey.includes("YOUR_")}
async function initCloud(){if(!cloudConfigured()){setStatus("Supabase未設定","warn");$("authMessage").textContent="まずSupabaseプロジェクトを作成し、config.jsにURLとPublishable keyを設定してください。現在は端末内保存で動作します。";return}try{supabaseClient=window.supabase.createClient(window.KEIBA_CONFIG.supabaseUrl,window.KEIBA_CONFIG.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const res=await supabaseClient.auth.getSession();session=res.data.session;await updateAuthUI();if(session)await initialCloudSync();supabaseClient.auth.onAuthStateChange(async(_event,s)=>{session=s;await updateAuthUI();if(s&&_event!=="INITIAL_SESSION")await initialCloudSync()})}catch(e){setStatus("接続エラー","error");$("authMessage").textContent="Supabaseの設定を確認してください。";console.error(e)}}
async function updateAuthUI(){const area=$("accountArea"),box=$("authBox");if(session){area.innerHTML=`<div class="account"><span>${escapeHtml(session.user.email||"")}</span><button id="signOut">ログアウト</button></div>`;box.classList.add("hide");$("authMessage").textContent="クラウド同期中。PC・iPhoneで同じアカウントにログインしてください。";setStatus("クラウド同期中","ok");$("signOut").onclick=async()=>{await supabaseClient.auth.signOut()}}else{area.innerHTML="";box.classList.remove("hide");if(cloudConfigured()){setStatus("未ログイン","warn");$("authMessage").textContent="ログインするとクラウド同期が有効になります。"}}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function signIn(){if(!supabaseClient)return alert("Supabaseの設定がまだ完了していません。");const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return alert("メールアドレスとパスワードを入力してください。");const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)alert("ログインできませんでした。\n"+error.message)}
async function signUp(){if(!supabaseClient)return alert("Supabaseの設定がまだ完了していません。");const email=$("email").value.trim(),password=$("password").value;if(!email||password.length<6)return alert("メールアドレスと6文字以上のパスワードを入力してください。");const{error}=await supabaseClient.auth.signUp({email,password});if(error)alert("登録できませんでした。\n"+error.message);else alert("登録処理を開始しました。メール確認が有効な場合は、届いたメールを確認してください。")}
function cloudRow(r,userId){return{user_id:userId,id:String(r.id),date:r.date||"1970-01-01",course:r.course||"その他",race:Math.round(toNumber(r.race)),type:r.type||"その他",inv:toNumber(r.inv),ret:toNumber(r.ret),memo:r.memo||"",updated_at:new Date().toISOString()}}
function fromCloud(r){return normalizeRecord(r,0)}
async function initialCloudSync(){if(!session||!supabaseClient)return;try{setStatus("同期中…","sync");const{data:rows,error}=await supabaseClient.from("keiba_records").select("*").eq("user_id",session.user.id);if(error)throw error;const cloud=(rows||[]).map(fromCloud);if(cloud.length===0&&data.length>0){const ok=confirm(`この端末には${data.length}件のV4データがあります。クラウドへ移行しますか？\n\n「OK」→既存データをクラウドへ保存\n「キャンセル」→クラウドは空のまま`);if(ok){const payload=data.map(r=>cloudRow(r,session.user.id));const{error:e}=await supabaseClient.from("keiba_records").upsert(payload,{onConflict:"user_id,id"});if(e)throw e;setStatus("同期済み","ok");return}}else if(cloud.length>0){const cloudIds=new Set(cloud.map(r=>String(r.id)));const missing=data.filter(r=>!cloudIds.has(String(r.id)));if(missing.length){const{error:e}=await supabaseClient.from("keiba_records").upsert(missing.map(r=>cloudRow(r,session.user.id)),{onConflict:"user_id,id"});if(e)throw e;cloud.push(...missing.map(normalizeRecord))}data=cloud;saveLocal();render()}setStatus("同期済み","ok")}catch(e){console.error(e);setStatus("同期エラー","error");$("authMessage").textContent="クラウド同期に失敗しました。端末内データは保持しています。";}}
async function upsertCloud(r){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_records").upsert(cloudRow(r,session.user.id),{onConflict:"user_id,id"});if(error){console.error(error);setStatus("同期エラー","error");alert("クラウド保存に失敗しました。端末内には保存されています。\n"+error.message)}else setStatus("同期済み","ok")}
async function deleteCloud(id){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_records").delete().eq("user_id",session.user.id).eq("id",String(id));if(error){console.error(error);setStatus("同期エラー","error");alert("クラウド削除に失敗しました。\n"+error.message)}}
async function clearCloud(){if(!session||!supabaseClient)return;const{error}=await supabaseClient.from("keiba_records").delete().eq("user_id",session.user.id);if(error){console.error(error);setStatus("同期エラー","error");alert("クラウド削除に失敗しました。\n"+error.message)}}
$("add").onclick=()=>open();$("close").onclick=close;$("modal").onclick=e=>{if(e.target.id==="modal")close()};
$("form").onsubmit=async e=>{e.preventDefault();const r={id:editId||String(Date.now()),date:$("date").value,course:$("course").value,race:toNumber($("race").value),type:$("type").value,inv:toNumber($("inv").value),ret:toNumber($("ret").value),memo:$("memo").value.trim()},i=data.findIndex(x=>String(x.id)===String(r.id));if(i>=0)data[i]=r;else data.push(r);saveLocal();render();close();await upsertCloud(r)};
$("records").onclick=async e=>{const b=e.target.closest("button");if(!b)return;const id=b.dataset.e||b.dataset.d;if(b.dataset.e){const r=data.find(x=>String(x.id)===String(id));if(r)open(r)}else if(confirm("この記録を削除しますか？")){data=data.filter(x=>String(x.id)!==String(id));saveLocal();render();await deleteCloud(id)}};
$("clear").onclick=async()=>{if(data.length&&confirm("すべての収支データを削除します。よろしいですか？")){data=[];saveLocal();render();await clearCloud()}};
$("months").onchange=draw;addEventListener("resize",draw);document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{periodMode=b.dataset.period;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));renderPeriod()});$("prevMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$("nextMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$("signIn").onclick=signIn;$("signUp").onclick=signUp;
$("exportData").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`keiba-note-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$("importData").onclick=()=>$("fileInput").click();$("fileInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const arr=JSON.parse(await f.text());if(!Array.isArray(arr))throw Error("配列ではありません");const imported=arr.map(normalizeRecord);if(!confirm(`${imported.length}件を復元します。現在のデータに追加・上書きしますか？`))return;const map=new Map(data.map(r=>[String(r.id),r]));imported.forEach(r=>map.set(String(r.id),r));data=[...map.values()];saveLocal();render();if(session&&supabaseClient){const{error}=await supabaseClient.from("keiba_records").upsert(data.map(r=>cloudRow(r,session.user.id)),{onConflict:"user_id,id"});if(error)throw error;setStatus("同期済み","ok")}alert("バックアップを復元しました。")}catch(err){alert("復元できませんでした。JSONバックアップを確認してください。\n"+err.message)}finally{e.target.value=""}};
render();initCloud();
